<a href="https://colab.research.google.com/github/johank1977/Interim_attestation_2/blob/main/%D0%9F%D1%80%D0%BE%D0%BC%D0%B5%D0%B6%D1%83%D1%82%D0%BE%D1%87%D0%BD%D0%B0%D1%8F_%D0%B0%D1%82%D1%82%D0%B5%D1%81%D1%82%D0%B0%D1%86%D0%B8%D1%8F_2_%D0%9A%D0%B0%D1%80%D0%B0%D0%B2%D0%B0%D0%B5%D0%B2_%D0%98%D0%93.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Промежуточная аттестация 2
Возьмите датасет «Финансовая отчётность российских компаний» и проанализируйте его с помощью Pandas или Polars.

ВАЖНО: Перед началом анализа сократите количество колонок до 20 и количество строк до 1000. Также, можете использовать streaming, чтобы не скачивать сразу весь датасет.

In [1]:
from datasets import load_dataset
import polars as pl

RFSD = load_dataset('irlspbru/RFSD', data_files="RFSD/year=2023/*.parquet", split="train")
RFSD = pl.DataFrame(RFSD.to_pandas())
RFSD

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

RFSD/year=2023/part-0.parquet:   0%|          | 0.00/555M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

shape: (3_219_569, 213)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ inn       ┆ ogrn      ┆ region    ┆ region_ta ┆ … ┆ line_6326 ┆ line_6330 ┆ line_6350 ┆ line_640 │
│ ---       ┆ ---       ┆ ---       ┆ xcode     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 0        │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ null      ┆ 904779668 ┆ moscow    ┆ 7700      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 8213      ┆ city      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 010000001 ┆ 121010000 ┆ adygeya   ┆ 0100      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 1         ┆ 2353      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 010000003 ┆ 102010000 ┆ adygeya   ┆ 0100      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 6         ┆ 2394      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 010000004 ┆ 121010000 ┆ adygeya   ┆ 0100      ┆ … ┆ null      ┆ null      ┆ null      ┆ 10.0     │
│ 3         ┆ 2364      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 010000006 ┆ 121010000 ┆ adygeya   ┆ 0100      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0.0      │
│ 8         ┆ 2375      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 990103770 ┆ 123990000 ┆ baikonur  ┆ 9900      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0         ┆ 0031      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 990103771 ┆ 123990000 ┆ baikonur  ┆ 9900      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 8         ┆ 0042      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 990108888 ┆ 112990100 ┆ baikonur  ┆ 9900      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 9         ┆ 0019      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 990199801 ┆ 111500000 ┆ baikonur  ┆ 9900      ┆ … ┆ null      ┆ -529.0    ┆ null      ┆ -5528.0  │
│ 3         ┆ 5614      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 990912535 ┆ 103500220 ┆ moscow    ┆ 5000      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 6         ┆ 0221      ┆ reg.      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Сокращаем колонки и строки, преобразуем полученный датасет в pandas

In [3]:
import random
import polars as pl
import pandas as pd

cols_to_keep = random.sample(RFSD.columns, 20)
df_sampled_cols = RFSD.select(RFSD.columns[:20])

# Случайные 1000 строк
df_reduced = df_sampled_cols.sample(n=1000, seed=42)
print(f"Размер: {df_reduced.shape}\n")

df_reduced

df_reduced = df_reduced.to_pandas()

df_reduced.head()

Размер: (1000, 20)

,inn,ogrn,region,region_taxcode,creation_date,dissolution_date,age,eligible,exemption_criteria,financial,filed,imputed,simplified,articulated,totals_adjustment,outlier,okved,okved_section,okpo,okopf
0,7743046150,1157746047018,moscow city,7700,2015-01-23,NaT,8.0,1.0,none,0.0,0.0,0.0,NaN,NaN,NaN,0.0,46.69.50,G,29183547,12300
1,4314006265,1204300003313,kirov,4300,2020-03-30,NaT,3.0,1.0,none,0.0,1.0,0.0,1.0,1.0,1.0,0.0,49.42,H,44016261,12300
2,9725024446,1197746671451,moscow city,7700,2019-11-13,NaT,4.0,1.0,none,0.0,1.0,0.0,1.0,1.0,1.0,0.0,96.04,S,42152379,12300
3,7703276742,1037739647175,moscow city,7700,2001-06-19,NaT,22.0,1.0,none,0.0,1.0,0.0,1.0,1.0,1.0,0.0,85.41,P,56696350,12300
4,7730272190,1217700619223,moscow city,7700,2021-12-17,NaT,2.0,1.0,none,0.0,1.0,0.0,1.0,1.0,1.0,0.0,46.73,G,71815007,12300

In [5]:
print(df_reduced.dtypes)

inn                           object
ogrn                          object
region                        object
region_taxcode                object
creation_date         datetime64[ms]
dissolution_date      datetime64[ms]
age                          float64
eligible                     float64
exemption_criteria            object
financial                    float64
filed                        float64
imputed                      float64
simplified                   float64
articulated                  float64
totals_adjustment            float64
outlier                      float64
okved                         object
okved_section                 object
okpo                          object
okopf                         object
dtype: object

Чистим данные, преобразуем типы данных соответственно в текст, дата, int или float, заменяем пропуски и NaN на 0

In [17]:
import pandas as pd
import numpy as np

def clean_dataframe(df):
    """
    Чистит DataFrame: заменяет NaN/NaT на 0, преобразует строки с числами в числовые типы,
    оставляя даты без изменений, а текстовые данные приводит к str.
    """
    # Копируем DataFrame, чтобы не менять оригинал
    cleaned_df = df.copy()

    # Заменяем все NaN и NaT на 0
    cleaned_df.fillna(0, inplace=True)


    for column in cleaned_df.columns:
        # Пропускаем столбцы с датами
        if pd.api.types.is_datetime64_any_dtype(cleaned_df[column]):
            continue

        # Пропускаем уже числовые столбцы
        if pd.api.types.is_numeric_dtype(cleaned_df[column]):
            # Для числовых столбцов явно приводим к int/float при необходимости
            if cleaned_df[column].dtype == 'float64' and (cleaned_df[column] % 1 == 0).all():
                cleaned_df[column] = cleaned_df[column].astype(int)
            continue

        # Пытаемся преобразовать в числовой тип
        converted_series = pd.to_numeric(cleaned_df[column], errors='coerce')

        # Если после преобразования есть не-NaN значения, значит столбец содержит числа
        if not converted_series.isna().all():
            # Заменяем NaN, появившиеся из нечисловых строк, на 0
            converted_series.fillna(0, inplace=True)
            # Оптимизируем тип: если все числа целые, преобразуем float в int
            if (converted_series % 1 == 0).all():
                converted_series = converted_series.astype(int)
            cleaned_df[column] = converted_series
        else:
            # Если преобразование не удалось — приводим к строковому типу
            #cleaned_df[column] = cleaned_df[column].astype(str)

            cleaned_df['region'] = cleaned_df['region'].astype('string')
            cleaned_df['exemption_criteria'] = cleaned_df['exemption_criteria'].astype('string')


    return cleaned_df


df = pd.DataFrame(df_reduced)

print("До очистки:")
print(df)
print("\nТипы данных до:")
print(df.dtypes)

cleaned_df = clean_dataframe(df_reduced)

print("\nПосле очистки:")
cleaned_df.head()
print("\nТипы данных после:")
print(cleaned_df.dtypes)

До очистки:
            inn           ogrn       region region_taxcode creation_date  \
0    7743046150  1157746047018  moscow city           7700    2015-01-23
1    4314006265  1204300003313        kirov           4300    2020-03-30
2    9725024446  1197746671451  moscow city           7700    2019-11-13
3    7703276742  1037739647175  moscow city           7700    2001-06-19
4    7730272190  1217700619223  moscow city           7700    2021-12-17
..          ...            ...          ...            ...           ...
995  2130221036  1202100007340    chuvashia           2100    2020-09-29
996  9723143021  1227700135651  moscow city           7700    2022-03-14
997  3025013455  1143025003791    astrakhan           3000    2014-11-26
998  2225087710  1072225010318  altai terr.           2200    2007-07-30
999  7111022877  1197154003287         tula           7100    2019-02-20

    dissolution_date   age  eligible exemption_criteria  financial  filed  \
0                NaT   8.0       1.0               none        0.0    0.0
1                NaT   3.0       1.0               none        0.0    1.0
2                NaT   4.0       1.0               none        0.0    1.0
3                NaT  22.0       1.0               none        0.0    1.0
4                NaT   2.0       1.0               none        0.0    1.0
..               ...   ...       ...                ...        ...    ...
995              NaT   3.0       1.0               none        0.0    1.0
996              NaT   1.0       1.0               none        0.0    1.0
997              NaT   9.0       1.0               none        0.0    1.0
998              NaT  16.0       1.0               none        0.0    1.0
999              NaT   4.0       1.0               none        0.0    1.0

     imputed  simplified  articulated  totals_adjustment  outlier     okved  \
0        0.0         NaN          NaN                NaN      0.0  46.69.50
1        0.0         1.0          1.0                1.0      0.0     49.42
2        0.0         1.0          1.0                1.0      0.0     96.04
3        0.0         1.0          1.0                1.0      0.0     85.41
4        0.0         1.0          1.0                1.0      0.0     46.73
..       ...         ...          ...                ...      ...       ...
995      0.0         1.0          1.0                1.0      0.0     69.10
996      0.0         1.0          1.0                1.0      0.0     45.20
997      0.0         1.0          1.0                1.0      0.0  74.90.31
998      0.0         1.0          1.0                1.0      0.0     43.22
999      0.0         1.0          1.0                0.0      0.0     94.99

    okved_section      okpo  okopf
0               G  29183547  12300
1               H  44016261  12300
2               S  42152379  12300
3               P  56696350  12300
4               G  71815007  12300
..            ...       ...    ...
995             M  45792760  12300
996             G  73749834  12300
997             M  22208422  12300
998             F  82603277  12300
999             S  36214691  20200

[1000 rows x 20 columns]

Типы данных до:
inn                           object
ogrn                          object
region                        object
region_taxcode                object
creation_date         datetime64[ms]
dissolution_date      datetime64[ms]
age                          float64
eligible                     float64
exemption_criteria            object
financial                    float64
filed                        float64
imputed                      float64
simplified                   float64
articulated                  float64
totals_adjustment            float64
outlier                      float64
okved                         object
okved_section                 object
okpo                          object
okopf                         object
dtype: object

После очистки:

Типы данных после:
inn                            int64
ogrn                           int64
region                string[python]
region_taxcode                 int64
creation_date         datetime64[ms]
dissolution_date               int64
age                            int64
eligible                       int64
exemption_criteria    string[python]
financial                      int64
filed                          int64
imputed                        int64
simplified                     int64
articulated                    int64
totals_adjustment              int64
outlier                        int64
okved                        float64
okved_section                  int64
okpo                           int64
okopf                          int64
dtype: object

/tmp/ipykernel_4035/516932956.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with datetime64[ms], please explicitly cast to a compatible dtype first.
  cleaned_df.fillna(0, inplace=True)

In [18]:
cleaned_df.head()

,inn,ogrn,region,region_taxcode,creation_date,dissolution_date,age,eligible,exemption_criteria,financial,filed,imputed,simplified,articulated,totals_adjustment,outlier,okved,okved_section,okpo,okopf
0,7743046150,1157746047018,moscow city,7700,2015-01-23,0,8,1,none,0,0,0,0,0,0,0,0.00,0,29183547,12300
1,4314006265,1204300003313,kirov,4300,2020-03-30,0,3,1,none,0,1,0,1,1,1,0,49.42,0,44016261,12300
2,9725024446,1197746671451,moscow city,7700,2019-11-13,0,4,1,none,0,1,0,1,1,1,0,96.04,0,42152379,12300
3,7703276742,1037739647175,moscow city,7700,2001-06-19,0,22,1,none,0,1,0,1,1,1,0,85.41,0,56696350,12300
4,7730272190,1217700619223,moscow city,7700,2021-12-17,0,2,1,none,0,1,0,1,1,1,0,46.73,0,71815007,12300

1. Выведите описательную статистику для датасета

In [19]:
print(cleaned_df.describe())

                inn          ogrn  region_taxcode               creation_date  \
count  1.000000e+03  1.000000e+03     1000.000000                        1000
mean   5.616937e+09  1.213499e+12     5453.183000  2013-08-29 14:35:31.200000
min    2.220019e+08  1.020200e+12      200.000000         1969-06-30 00:00:00
25%    3.662612e+09  1.095404e+12     3600.000000         2008-12-21 00:00:00
50%    5.990507e+09  1.155958e+12     6000.000000         2015-03-05 00:00:00
75%    7.720884e+09  1.207325e+12     7700.000000         2020-03-12 18:00:00
max    9.901034e+09  5.177746e+12     9900.000000         2023-12-29 00:00:00
std    2.556166e+09  5.203877e+11     2365.178117                         NaN

       dissolution_date          age     eligible  financial        filed  \
count            1000.0  1000.000000  1000.000000     1000.0  1000.000000
mean                0.0     9.863000     0.987000        0.0     0.705000
min                 0.0     0.000000     0.000000        0.0     0.000000
25%                 0.0     3.000000     1.000000        0.0     0.000000
50%                 0.0     8.000000     1.000000        0.0     1.000000
75%                 0.0    15.000000     1.000000        0.0     1.000000
max                 0.0    54.000000     1.000000        0.0     1.000000
std                 0.0     8.187018     0.113331        0.0     0.456271

           imputed   simplified  articulated  totals_adjustment  outlier  \
count  1000.000000  1000.000000   1000.00000        1000.000000   1000.0
mean      0.016000     0.435000      0.68300           0.638000      0.0
min       0.000000     0.000000      0.00000           0.000000      0.0
25%       0.000000     0.000000      0.00000           0.000000      0.0
50%       0.000000     0.000000      1.00000           1.000000      0.0
75%       0.000000     1.000000      1.00000           1.000000      0.0
max       1.000000     1.000000      1.00000           1.000000      0.0
std       0.125538     0.496005      0.46554           0.480819      0.0

             okved  okved_section          okpo         okopf
count  1000.000000         1000.0  1.000000e+03   1000.000000
mean     42.235360            0.0  4.441685e+07  14713.189000
min       0.000000            0.0  0.000000e+00  12247.000000
25%      12.742500            0.0  1.948504e+07  12300.000000
50%      46.450000            0.0  4.447907e+07  12300.000000
75%      64.200000            0.0  7.056154e+07  12300.000000
max      96.090000            0.0  9.996398e+07  75505.000000
std      29.201639            0.0  2.986702e+07   9589.189455

In [21]:
import pandas as pd
import numpy as np

df = cleaned_df

print("=== ИНФОРМАЦИЯ О ТИПАХ ДАННЫХ ===")
print(df.info())
print("\n" + "="*40 + "\n")

print("=== ПОДРОБНАЯ ИНФОРМАЦИЯ ===")
df.info()
print("\n" + "="*40 + "\n")

print("=== КОЛИЧЕСТВО ПРОПУСКОВ ПО СТОЛБЦАМ ===")
print(df.isna().sum())
print("\n" + "="*40 + "\n")

print("=== ПРОЦЕНТ ПРОПУСКОВ ===")
print((df.isna().sum() / len(df)) * 100)
print("\n" + "="*40 + "\n")

print("=== СТРОКИ С ПРОПУСКАМИ ===")
print(df[df.isna().any(axis=1)])

=== ИНФОРМАЦИЯ О ТИПАХ ДАННЫХ ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   inn                 1000 non-null   int64
 1   ogrn                1000 non-null   int64
 2   region              1000 non-null   string
 3   region_taxcode      1000 non-null   int64
 4   creation_date       1000 non-null   datetime64[ms]
 5   dissolution_date    1000 non-null   int64
 6   age                 1000 non-null   int64
 7   eligible            1000 non-null   int64
 8   exemption_criteria  1000 non-null   string
 9   financial           1000 non-null   int64
 10  filed               1000 non-null   int64
 11  imputed             1000 non-null   int64
 12  simplified          1000 non-null   int64
 13  articulated         1000 non-null   int64
 14  totals_adjustment   1000 non-null   int64
 15  outlier             1000 non-null   int64
 16  okved               1000 non-null   float64
 17  okved_section       1000 non-null   int64
 18  okpo                1000 non-null   int64
 19  okopf               1000 non-null   int64
dtypes: datetime64[ms](1), float64(1), int64(16), string(2)
memory usage: 156.4 KB
None

========================================

=== ПОДРОБНАЯ ИНФОРМАЦИЯ ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   inn                 1000 non-null   int64
 1   ogrn                1000 non-null   int64
 2   region              1000 non-null   string
 3   region_taxcode      1000 non-null   int64
 4   creation_date       1000 non-null   datetime64[ms]
 5   dissolution_date    1000 non-null   int64
 6   age                 1000 non-null   int64
 7   eligible            1000 non-null   int64
 8   exemption_criteria  1000 non-null   string
 9   financial           1000 non-null   int64
 10  filed               1000 non-null   int64
 11  imputed             1000 non-null   int64
 12  simplified          1000 non-null   int64
 13  articulated         1000 non-null   int64
 14  totals_adjustment   1000 non-null   int64
 15  outlier             1000 non-null   int64
 16  okved               1000 non-null   float64
 17  okved_section       1000 non-null   int64
 18  okpo                1000 non-null   int64
 19  okopf               1000 non-null   int64
dtypes: datetime64[ms](1), float64(1), int64(16), string(2)
memory usage: 156.4 KB

========================================

=== КОЛИЧЕСТВО ПРОПУСКОВ ПО СТОЛБЦАМ ===
inn                   0
ogrn                  0
region                0
region_taxcode        0
creation_date         0
dissolution_date      0
age                   0
eligible              0
exemption_criteria    0
financial             0
filed                 0
imputed               0
simplified            0
articulated           0
totals_adjustment     0
outlier               0
okved                 0
okved_section         0
okpo                  0
okopf                 0
dtype: int64

========================================

=== ПРОЦЕНТ ПРОПУСКОВ ===
inn                   0.0
ogrn                  0.0
region                0.0
region_taxcode        0.0
creation_date         0.0
dissolution_date      0.0
age                   0.0
eligible              0.0
exemption_criteria    0.0
financial             0.0
filed                 0.0
imputed               0.0
simplified            0.0
articulated           0.0
totals_adjustment     0.0
outlier               0.0
okved                 0.0
okved_section         0.0
okpo                  0.0
okopf                 0.0
dtype: float64

========================================

=== СТРОКИ С ПРОПУСКАМИ ===
Empty DataFrame
Columns: [inn, ogrn, region, region_taxcode, creation_date, dissolution_date, age, eligible, exemption_criteria, financial, filed, imputed, simplified, articulated, totals_adjustment, outlier, okved, okved_section, okpo, okopf]
Index: []

2. Постройте гистограммы для трех колонок, которые, на ваш взгляд, могут содержать полезную информацию. Выясните, есть ли в этих колонках выбросы и аномалии (значения, которые сильно отличаются от остальных значений или кажутся странными/некорректными).

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


# Создаём пример DataFrame (замените на ваши данные)
np.random.seed(42)
df = pd.DataFrame({
    'age': np.random.normal(35, 12, 1000),  # возраст
    'salary': np.random.lognormal(10, 0.8, 1000),  # зарплата (асимметричное распределение)
    'experience_years': np.random.exponential(5, 1000)  # опыт работы
})

# Добавляем несколько выбросов для демонстрации
df.loc[10] = [85, 500000, 40]
df.loc[20] = [20, 200000, 35]
df.loc[30] = [15, 80000, 50]

# Настройка визуализации
plt.figure(figsize=(15, 12))

# Гистограмма 1: Возраст
plt.subplot(3, 2, 1)
df['age'].hist(bins=30, color='skyblue', edgecolor='black', alpha=0.7)
plt.title('Распределение возраста')
plt.xlabel('Возраст')
plt.ylabel('Количество наблюдений')

# Boxplot для возраста
plt.subplot(3, 2, 2)
sns.boxplot(y=df['age'], color='lightblue')
plt.title('Boxplot: Возраст')
plt.ylabel('Возраст')

# Гистограмма 2: Зарплата
plt.subplot(3, 2, 3)
df['salary'].hist(bins=30, color='lightgreen', edgecolor='black', alpha=0.7)
plt.title('Распределение зарплаты')
plt.xlabel('Зарплата')
plt.ylabel('Количество наблюдений')

# Boxplot для зарплаты
plt.subplot(3, 2, 4)
sns.boxplot(y=df['salary'], color='lightgreen')
plt.title('Boxplot: Зарплата')
plt.ylabel('Зарплата')

# Гистограмма 3: Опыт работы
plt.subplot(3, 2, 5)
df['experience_years'].hist(bins=30, color='salmon', edgecolor='black', alpha=0.7)
plt.title('Распределение опыта работы')
plt.xlabel('Опыт (лет)')
plt.ylabel('Количество наблюдений')

# Boxplot для опыта работы
plt.subplot(3, 2, 6)
sns.boxplot(y=df['experience_years'], color='salmon')
plt.title('Boxplot: Опыт работы')
plt.ylabel('Опыт (лет)')

plt.tight_layout()
plt.show()